### ISSUE TITLE
Get loading state

### ISSUE THREAD

**Issue by Nichtmetall** [keycloakify/oidc-spa#15]
Hey, me again. I would like to be able to display a component while the authentication is still loading. Preferably via useOidc, also possible in the OidcProvider. For example, if you have logged in, but the forwarding to the application takes a while.

**Comment by garronej** [comment]
Hello @Nichtmetall,  

I think this is possible already.  
You can provide a fallback node as props to the <OidcProvider />.  

https://docs.oidc-spa.dev/getting-started/usage  

<img width="722" alt="image" src="https://github.com/keycloakify/oidc-spa/assets/6702424/1c8bd3d3-5477-4aaf-b07c-a1d9f272a8af">

**Comment by Nichtmetall** [comment]
Hey @garronej ,
thank you very much!
