### ISSUE TITLE
I'm experiencing flickering issues with this library whenever I switch between tabs.

### ISSUE THREAD

**Issue by syama-aot** [keycloakify/oidc-spa#21]
I found this new package very promising and decided to integrate it into my project. However, I encountered an issue with flickering whenever I switched between tabs. Can you assist me with resolving this problem?. When I used **react-keycloak-provider.** I haven't faced the flickering issue .

**Comment by garronej** [comment]
Hello @syama-aot,  
Sure thing! Brovide me with the necessary information to reproduce the issue and I will look into it!

**Comment by itsam** [comment]
I am using the library in production with Vite, tanstack router and chakra with no issues... What kind of flickering you mean exactly?

**Comment by syama-aot** [comment]
Its my bad. Issue fixed. Thank you.
