### ISSUE TITLE
autoLogout: not working when tab is inactive

### ISSUE THREAD

**Issue by laurentC35** [keycloakify/oidc-spa#23]
L'autoLogout est basée sur la fonction setTimeout du navigateur.

Cependant, lorsque l'onglet est inactif, les navigateurs (pour des raisons d'économie d'énergie) arrêtent les compteurs des timeout.
La déconnexion par inactivité ne fonctionne donc pas dans ces cas là.

Une solution serait d'utilisé les web-workers, qui ne sont pas affecté par ce pb.
Voilà un peu de documentation : https://isamatov.com/prevent-timers-stopping-javascript/

**Comment by garronej** [comment]
Very interesting, thanks for the heads up.  

This is critical mostly for automatic renewal of the access token.  

I've released a new version levraging a polyfill of `setTimeout` based on web workers.

**Comment by laurentC35** [comment]
Thanks a lot for your fix, I appreciate it
