### ISSUE TITLE
User management action redirect fails in Keycloak 26

### ISSUE THREAD

**Issue by tobias-kellner** [keycloakify/oidc-spa#38]
I have problems after upgrading from Keycloak 25 to Keycloak 26.
When I click on the cancel or submit buttons of a [user management action](https://docs.oidc-spa.dev/documentation/user-account-management) like `UPDATE_PASSWORD` or `UPDATE_PROFILE` I get redirected to my application but I see a white page.

This redirect has some parameters. It looks like in Keycloak 26 a new parameter was added. This is the URL I get redirected to:
https://my-application.com?oidc-spa_config_hash=some-value&oidc-spa_result_omit=some-value&oidc-spa_intent=some-value&state=some-value&session_state=some-value&iss=some-value&kc_action=UPDATE_PROFILE&kc_action_status=success&code=some-value

If I compare this with an old redirect URL I can see that the parameter `kc_action=UPDATE_PROFILE` was added. When I remove this parameter manually the page works as expected.

**Comment by garronej** [comment]
Fixed in oidc-spa@5.4.4.  
Thanks again for reporting

**Comment by tobias-kellner** [comment]
I can confirm: v5.4.4 fixes the problem.
Thanks for the fast fix!
